/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AliasVerificationResult
 */
export interface AliasVerificationResult {
    /**
     * 
     * @type {string}
     * @memberof AliasVerificationResult
     */
    aliasId: string;
    /**
     * 
     * @type {boolean}
     * @memberof AliasVerificationResult
     */
    isVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof AliasVerificationResult
     */
    message?: string;
}

export function AliasVerificationResultFromJSON(json: any): AliasVerificationResult {
    return AliasVerificationResultFromJSONTyped(json, false);
}

export function AliasVerificationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasVerificationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aliasId': json['aliasId'],
        'isVerified': json['isVerified'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function AliasVerificationResultToJSON(value?: AliasVerificationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aliasId': value.aliasId,
        'isVerified': value.isVerified,
        'message': value.message,
    };
}


