/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Representation of a alias
 * @export
 * @interface AliasProjection
 */
export interface AliasProjection {
    /**
     * 
     * @type {string}
     * @memberof AliasProjection
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AliasProjection
     */
    inboxId: string;
    /**
     * 
     * @type {string}
     * @memberof AliasProjection
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AliasProjection
     */
    pendingEmailAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AliasProjection
     */
    useThreads?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AliasProjection
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AliasProjection
     */
    verifiedEmailAddress?: string;
}

export function AliasProjectionFromJSON(json: any): AliasProjection {
    return AliasProjectionFromJSONTyped(json, false);
}

export function AliasProjectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AliasProjection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'inboxId': json['inboxId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'pendingEmailAddress': !exists(json, 'pendingEmailAddress') ? undefined : json['pendingEmailAddress'],
        'useThreads': !exists(json, 'useThreads') ? undefined : json['useThreads'],
        'userId': json['userId'],
        'verifiedEmailAddress': !exists(json, 'verifiedEmailAddress') ? undefined : json['verifiedEmailAddress'],
    };
}

export function AliasProjectionToJSON(value?: AliasProjection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'inboxId': value.inboxId,
        'name': value.name,
        'pendingEmailAddress': value.pendingEmailAddress,
        'useThreads': value.useThreads,
        'userId': value.userId,
        'verifiedEmailAddress': value.verifiedEmailAddress,
    };
}


