/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Alias
 */
export interface Alias {
    /**
     * 
     * @type {Date}
     * @memberof Alias
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    inboxId: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    pendingEmailAddress?: string;
    /**
     * 
     * @type {Date}
     * @memberof Alias
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Alias
     */
    useThreads?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Alias
     */
    verifiedEmailAddress?: string;
}

export function AliasFromJSON(json: any): Alias {
    return AliasFromJSONTyped(json, false);
}

export function AliasFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alias {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'inboxId': json['inboxId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'pendingEmailAddress': !exists(json, 'pendingEmailAddress') ? undefined : json['pendingEmailAddress'],
        'updatedAt': (new Date(json['updatedAt'])),
        'useThreads': !exists(json, 'useThreads') ? undefined : json['useThreads'],
        'userId': json['userId'],
        'verifiedEmailAddress': !exists(json, 'verifiedEmailAddress') ? undefined : json['verifiedEmailAddress'],
    };
}

export function AliasToJSON(value?: Alias | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': (value.createdAt.toISOString()),
        'id': value.id,
        'inboxId': value.inboxId,
        'name': value.name,
        'pendingEmailAddress': value.pendingEmailAddress,
        'updatedAt': (value.updatedAt.toISOString()),
        'useThreads': value.useThreads,
        'userId': value.userId,
        'verifiedEmailAddress': value.verifiedEmailAddress,
    };
}


