/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create anonymous email alias options. Email aliases can be used to mask real email addresses behind an ID
 * @export
 * @interface CreateAnonymousAliasOptions
 */
export interface CreateAnonymousAliasOptions {
    /**
     * Email address to be hidden behind alias
     * @type {string}
     * @memberof CreateAnonymousAliasOptions
     */
    emailAddress?: string;
}

export function CreateAnonymousAliasOptionsFromJSON(json: any): CreateAnonymousAliasOptions {
    return CreateAnonymousAliasOptionsFromJSONTyped(json, false);
}

export function CreateAnonymousAliasOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnonymousAliasOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailAddress': !exists(json, 'emailAddress') ? undefined : json['emailAddress'],
    };
}

export function CreateAnonymousAliasOptionsToJSON(value?: CreateAnonymousAliasOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailAddress': value.emailAddress,
    };
}


