/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SentEmail
 */
export interface SentEmail {
    /**
     * 
     * @type {Array<string>}
     * @memberof SentEmail
     */
    attachments?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SentEmail
     */
    bcc?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    bodyMD5Hash?: string;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    bodyS3Key?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SentEmail
     */
    cc?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    charset?: string;
    /**
     * 
     * @type {Date}
     * @memberof SentEmail
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    inboxId: string;
    /**
     * 
     * @type {boolean}
     * @memberof SentEmail
     */
    isHTML?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    subject?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SentEmail
     */
    to?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof SentEmail
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SentEmail
     */
    userId: string;
}

export function SentEmailFromJSON(json: any): SentEmail {
    return SentEmailFromJSONTyped(json, false);
}

export function SentEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'bcc': !exists(json, 'bcc') ? undefined : json['bcc'],
        'bodyMD5Hash': !exists(json, 'bodyMD5Hash') ? undefined : json['bodyMD5Hash'],
        'bodyS3Key': !exists(json, 'bodyS3Key') ? undefined : json['bodyS3Key'],
        'cc': !exists(json, 'cc') ? undefined : json['cc'],
        'charset': !exists(json, 'charset') ? undefined : json['charset'],
        'createdAt': (new Date(json['createdAt'])),
        'from': !exists(json, 'from') ? undefined : json['from'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'inboxId': json['inboxId'],
        'isHTML': !exists(json, 'isHTML') ? undefined : json['isHTML'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'updatedAt': (new Date(json['updatedAt'])),
        'userId': json['userId'],
    };
}

export function SentEmailToJSON(value?: SentEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attachments': value.attachments,
        'bcc': value.bcc,
        'bodyMD5Hash': value.bodyMD5Hash,
        'bodyS3Key': value.bodyS3Key,
        'cc': value.cc,
        'charset': value.charset,
        'createdAt': (value.createdAt.toISOString()),
        'from': value.from,
        'id': value.id,
        'inboxId': value.inboxId,
        'isHTML': value.isHTML,
        'subject': value.subject,
        'to': value.to,
        'updatedAt': (value.updatedAt.toISOString()),
        'userId': value.userId,
    };
}


